shell.run('wget https://raw.githubusercontent.com/ChickChicky/cc-turtle-remote/main/turtle/startup.lua')
shell.run('wget https://raw.githubusercontent.com/ChickChicky/cc-turtle-remote/main/turtle/json.lua')
shell.run('wget https://raw.githubusercontent.com/ChickChicky/cc-turtle-remote/main/turtle/turtle_wrapper.lua')
shell.run('wget https://raw.githubusercontent.com/ChickChicky/cc-turtle-remote/main/turtle/websocket.lua')
shell.run('wget https://raw.githubusercontent.com/ChickChicky/cc-turtle-remote/main/turtle/data.json')